### ISSUE TITLE
AttributeError: 'DenseNet' object has no attribute 'network'

### ISSUE THREAD

**Issue by prwe98** [prwe98/Machine_Learning_Practice#1]
https://github.com/prwe98/Machine_Learning_Practice/blob/6822eaeb9180d2aea42cb482bbfbed98d5feb131/modeling_neural_network.py#L136
https://github.com/prwe98/Machine_Learning_Practice/blob/6822eaeb9180d2aea42cb482bbfbed98d5feb131/modeling_neural_network.py#L264
when I try to test the densenet  following problems arise:

Traceback (most recent call last):
  File "F:/bestpractice/modeling_neural_network.py", line 264, in <module>
    model = DenseNet(input_dims, hidden_dims=[16], dropout=0.0)
  File "F:/bestpractice/modeling_neural_network.py", line 131, in __init__
    self.network.extend([
  File "F:\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DenseNet' object has no attribute 'network'

**Comment by prwe98** [comment]
The problem has been solved in v0.1.1
